# THIS FILE IS GENERATED BY A TOOL. PLEASE DO NOT MODIFY MANUALLY.

replacement_fixups = {
    "2010. évi CLIII. törvény": [
        {
            "needle": "a „15 munkanapon belül” szöveg, valamint 140. § (6) bekezdésében a 8 munkanapon belül” szövegrész helyébe",
            "replacement": "a „15 munkanapon belül” szöveg, valamint 140. § (6) bekezdésében a „8 munkanapon belül” szövegrész helyébe"
        }
    ],
    "2010. évi CLIX. törvény": [
        {
            "needle": "résztvevő a rendszerüzemeltető számára ismert;”",
            "replacement": "résztvevő a rendszerüzemeltető számára ismert;"
        }
    ],
    "2010. évi CLXXII. törvény": [
        {
            "needle": "tesz közzé.”",
            "replacement": "tesz közzé."
        },
        {
            "needle": "vonatokról, valamint vasúti állomásról és megállóhelyről a szolgáltató a honlapján tájékoztatást tesz közzé.”",
            "replacement": "vonatokról, valamint vasúti állomásról és megállóhelyről a szolgáltató a honlapján tájékoztatást tesz közzé."
        },
        {
            "needle": "szövegrész helyébe a „miniszterrel egyetértésben” szöveg, 74. § (1) bekezdés m) pontjában az „is – „ szövegrész",
            "replacement": "szövegrész helyébe a „miniszterrel egyetértésben” szöveg, 74. § (1) bekezdés m) pontjában az „is – ” szövegrész"
        },
        {
            "needle": "helyébe az – egyetértésben” szöveg, 74. § (2) bekezdés k) és l) pontjában a „miniszter az” szövegrész helyébe",
            "replacement": "helyébe az „– egyetértésben” szöveg, 74. § (2) bekezdés k) és l) pontjában a „miniszter az” szövegrész helyébe"
        }
    ],
    "2010. évi CLXXIII. törvény": [
        {
            "needle": "a „jelölt tag” szövegrész helyébe a „kinevezett tag” szöveg lép.”",
            "replacement": "a „jelölt tag” szövegrész helyébe a „kinevezett tag” szöveg lép."
        }
    ],
    "2010. évi CLXXX. törvény": [
        {
            "needle": "jogosult, ha a szerződésében a teljes önkéntesség tényét nem rögzítette.”",
            "replacement": "jogosult, ha a szerződésében a teljes önkéntesség tényét nem rögzítette."
        }
    ],
    "2010. évi CLXXXIII. törvény": [
        {
            "needle": "(4) E törvény 67. §-a, 165. § (2) bekezdés e) és f) pontja 2011. szeptember 1-jén lép hatályba.”",
            "replacement": "(4) E törvény 67. §-a, 165. § (2) bekezdés e) és f) pontja 2011. szeptember 1-jén lép hatályba."
        }
    ],
    "2010. évi CXLVIII. törvény": [
        {
            "needle": "(7) bekezdésében a „huszonkét” szövegrész helyébe a „harminc” szöveg lép.”",
            "replacement": "(7) bekezdésében a „huszonkét” szövegrész helyébe a „harminc” szöveg lép."
        }
    ],
    "2011. évi CCIX. törvény": [
        {
            "needle": "alkalmazni.”",
            "replacement": "alkalmazni.””"
        }
    ],
    "2011. évi CCVII. törvény": [
        {
            "needle": "g) 2. számú melléklet 10. pontja.”",
            "replacement": "g) 2. számú melléklet 10. pontja."
        }
    ],
    "2011. évi CLIV. törvény": [
        {
            "needle": "g) 92. § (3) bekezdés első mondatában az ”, illetve a megyei önkormányzat a településen, illetve a megyében”",
            "replacement": "g) 92. § (3) bekezdés első mondatában az „, illetve a megyei önkormányzat a településen, illetve a megyében”"
        },
        {
            "needle": "j) 89/B. § (7) bekezdésében a „megyei önkormányzat” szövegrész helyébe a Kormány általános hatáskörű területi",
            "replacement": "j) 89/B. § (7) bekezdésében a „megyei önkormányzat” szövegrész helyébe a „Kormány általános hatáskörű területi"
        }
    ],
    "2011. évi CLXI. törvény": [
        {
            "needle": ",,A munkaköri kötelességeimet részrehajlás nélkül, lelkiismeretesen, kizárólag a jogszabályoknak megfelelően,",
            "replacement": "„A munkaköri kötelességeimet részrehajlás nélkül, lelkiismeretesen, kizárólag a jogszabályoknak megfelelően,"
        }
    ],
    "2011. évi CLXII. törvény": [
        {
            "needle": ",,Fogadom, hogy a rám bízott ügyeket tisztességes eljárásban, részrehajlás nélkül, lelkiismeretesen, kizárólag",
            "replacement": "„Fogadom, hogy a rám bízott ügyeket tisztességes eljárásban, részrehajlás nélkül, lelkiismeretesen, kizárólag"
        }
    ],
    "2011. évi CLXVI. törvény": [
        {
            "needle": "„(A kiadások fedezetét a következő bevételek képezik:",
            "replacement": "(A kiadások fedezetét a következő bevételek képezik:"
        }
    ],
    "2011. évi CLXX. törvény": [
        {
            "needle": "(2) Az 1–25. §, a 27. § és az 1. melléklet 2012. január 1-jén lép hatályba.”",
            "replacement": "(2) Az 1–25. §, a 27. § és az 1. melléklet 2012. január 1-jén lép hatályba."
        }
    ],
    "2011. évi CLXXII. törvény": [
        {
            "needle": "a bi) alpontjában a „Magyar Köztársaság” szövegrész helyébe a „Magyarország” szöveg lép.”",
            "replacement": "a bi) alpontjában a „Magyar Köztársaság” szövegrész helyébe a „Magyarország” szöveg lép."
        }
    ],
    "2011. évi CLXXIII. törvény": [
        {
            "needle": "„kihirdetésétől” szövegrész helyébe a „kézbesítésétől” szöveg lép.”",
            "replacement": "„kihirdetésétől” szövegrész helyébe a „kézbesítésétől” szöveg lép."
        }
    ],
    "2011. évi CLXXV. törvény": [
        {
            "needle": "„ „45. § A Tao tv. a következő 29/Q. §-sal egészül ki:",
            "replacement": "„45. § A Tao tv. a következő 29/Q. §-sal egészül ki:"
        },
        {
            "needle": "szöveg lép .",
            "replacement": "szöveg lép .”"
        }
    ],
    "2011. évi CLXXVI. törvény": [
        {
            "needle": "(3) bekezdésében foglaltakon túl – „ szövegrész helyébe az „– az 5/A. § (3) bekezdésében és (11) bekezdésének",
            "replacement": "(3) bekezdésében foglaltakon túl – ” szövegrész helyébe az „– az 5/A. § (3) bekezdésében és (11) bekezdésének"
        },
        {
            "needle": "g) 4. számú melléklete.”",
            "replacement": "g) 4. számú melléklete."
        }
    ],
    "2011. évi CLXXXIV. törvény": [
        {
            "needle": "helyébe a ”kormányzati szolgálati, közszolgálati, vagy” szöveg,",
            "replacement": "helyébe a „kormányzati szolgálati, közszolgálati, vagy” szöveg,"
        }
    ],
    "2011. évi CV. törvény": [
        {
            "needle": "b) ha egyenlőtlen munkaidő-beosztásban kíván dolgozni, a munkaidő-beosztásra vonatkozó javaslatáról.”",
            "replacement": "b) ha egyenlőtlen munkaidő-beosztásban kíván dolgozni, a munkaidő-beosztásra vonatkozó javaslatáról."
        },
        {
            "needle": "történő foglalkoztatásnak a Módtv. hatálybalépését követően ledolgozott időtartama tekintetében kell alkalmazni.”",
            "replacement": "történő foglalkoztatásnak a Módtv. hatálybalépését követően ledolgozott időtartama tekintetében kell alkalmazni."
        }
    ],
    "2011. évi CVI. törvény": [
        {
            "needle": "(6) bekezdésében, valamint 37/C. § (8) bekezdés a) pontjában a ”bérpótló juttatásra” szövegrész helyébe",
            "replacement": "(6) bekezdésében, valamint 37/C. § (8) bekezdés a) pontjában a „bérpótló juttatásra” szövegrész helyébe"
        }
    ],
    "2011. évi CVII. törvény": [
        {
            "needle": "szempontjából nem megfelelő, akkor annak üzemben tartóját terhelik.”",
            "replacement": "szempontjából nem megfelelő, akkor annak üzemben tartóját terhelik."
        },
        {
            "needle": "49/a. Helymeghatározási szolgáltatás: olyan kapcsolódó szolgáltatás, amelyet az előfizető vagy felhasználó",
            "replacement": "„49/a. Helymeghatározási szolgáltatás: olyan kapcsolódó szolgáltatás, amelyet az előfizető vagy felhasználó"
        },
        {
            "needle": "szöveg,”, a 31. § (3) bekezdésében „Az (1)–(2) bekezdésben” szövegrész helyébe „A (2) bekezdésben” szöveg, a 33. §",
            "replacement": "szöveg, a 31. § (3) bekezdésében „Az (1)–(2) bekezdésben” szövegrész helyébe „A (2) bekezdésben” szöveg, a 33. §"
        },
        {
            "needle": "rendelkezések alkalmazandók.”",
            "replacement": "rendelkezések alkalmazandók."
        }
    ],
    "2011. évi CXCIII. törvény": [
        {
            "needle": "megszüntetéséről a befektetési alapkezelő dönt, amelynek során az ”IL” sorozatjelű befektetési jegyeket az alap",
            "replacement": "megszüntetéséről a befektetési alapkezelő dönt, amelynek során az „IL” sorozatjelű befektetési jegyeket az alap"
        },
        {
            "needle": "a „2011. december 31-ig” szövegrész helyébe a „2012. június 30-ig” szöveg lép.”",
            "replacement": "a „2011. december 31-ig” szövegrész helyébe a „2012. június 30-ig” szöveg lép."
        },
        {
            "needle": "hatósági felügyeleti,” szöveg lép.”",
            "replacement": "hatósági felügyeleti,” szöveg lép."
        },
        {
            "needle": "valamint e szolgáltatások fedezetéről szóló 1997. évi LXXX. törvény 3. § (2) bekezdése szerinti kötelezettségét.”",
            "replacement": "valamint e szolgáltatások fedezetéről szóló 1997. évi LXXX. törvény 3. § (2) bekezdése szerinti kötelezettségét.””"
        }
    ],
    "2011. évi CXCVII. törvény": [
        {
            "needle": "bocsátott vagyonból.”",
            "needle_prev_lines": [
                "biztosíték teljesítéséért a vezetőtől való behajthatatlanság esetén kezesként felel. A külföldi székhelyű vállalkozás",
                "az említett kezesi kötelezettségéből eredő fizetési kötelezettségét nem teljesítheti a fióktelepe rendelkezésére"
            ],
            "replacement": "bocsátott vagyonból."
        },
        {
            "needle": "(8) bekezdése.”",
            "replacement": "(8) bekezdése."
        }
    ],
    "2011. évi CXLIV. törvény": [
        {
            "needle": "Ireland signed at Budapest on 28th November 1977 (”the prior Convention”) shall cease to be effective from the dates",
            "replacement": "Ireland signed at Budapest on 28th November 1977 („the prior Convention”) shall cease to be effective from the dates"
        }
    ],
    "2011. évi CXLV. törvény": [
        {
            "needle": "\"C O N V E N T I O N",
            "replacement": "„C O N V E N T I O N"
        }
    ],
    "2011. évi CXXV. törvény": [
        {
            "needle": "a 2012. január–március tárgynegyedévre kell alkalmazni.”",
            "needle_prev_lines": [
                "CXXV. törvénnyel megállapított 33. § (2), (3), (6) bekezdéseit 2012. január 1. napjától és első alkalommal"
            ],
            "replacement": "a 2012. január–március tárgynegyedévre kell alkalmazni."
        }
    ],
    "2011. évi CXXXVI. törvény": [
        {
            "needle": "2. § Az Országgyűlés Szigetvár városnak a „Leghősiesebb Város” ( „Civitas Invicta\") címet adományozza.",
            "replacement": "2. § Az Országgyűlés Szigetvár városnak a „Leghősiesebb Város” ( „Civitas Invicta”) címet adományozza."
        }
    ],
    "2011. évi LIX. törvény": [
        {
            "needle": "szövegrész.”",
            "replacement": "szövegrész."
        },
        {
            "needle": "(17) A VET. 171/A. §-a 2012. szeptember 30-án hatályát veszti.”",
            "replacement": "(17) A VET. 171/A. §-a 2012. szeptember 30-án hatályát veszti."
        }
    ],
    "2011. évi LXV. törvény": [
        {
            "needle": "Szlovén Köztársaság A 20. cikkben kijelölt szolgálatok",
            "replacement": "Szlovén Köztársaság A 20. cikkben kijelölt szolgálatok”"
        }
    ],
    "2011. évi LXXXIV. törvény": [
        {
            "needle": "a silent partner ( „stiller Gesellschafter“) from his participation as such, or from a loan with an interest rate linked to",
            "replacement": "a silent partner ( „stiller Gesellschafter”) from his participation as such, or from a loan with an interest rate linked to"
        },
        {
            "needle": "borrower’s profit ( „partiarisches Darlehen“) or from profit sharing bonds ( „Gewinnobligationen“) within",
            "replacement": "borrower’s profit ( „partiarisches Darlehen”) or from profit sharing bonds ( „Gewinnobligationen”) within"
        }
    ],
    "2011. évi LXXXVI. törvény": [
        {
            "needle": "(5) E törvény 2012. május 2-án hatályát veszti.”",
            "replacement": "(5) E törvény 2012. május 2-án hatályát veszti."
        }
    ],
    "2011. évi XCVI. törvény": [
        {
            "needle": "35. § (1) A MódTv. 82. § (1) bekezdésében a „2010. október 31.” szövegrész helyébe a 2011. április 30.” szöveg lép.",
            "replacement": "35. § (1) A MódTv. 82. § (1) bekezdésében a „2010. október 31.” szövegrész helyébe a „2011. április 30.” szöveg lép."
        },
        {
            "needle": "Zsigmond Király Főiskola, Budapest\"",
            "replacement": "Zsigmond Király Főiskola, Budapest”"
        }
    ],
    "2011. évi XLVI. törvény": [
        {
            "needle": "kifizetett bevétel, illetve a jogviszony megszűnésekor a magánszemélyt megillető jubileumi jutalom.\"",
            "replacement": "kifizetett bevétel, illetve a jogviszony megszűnésekor a magánszemélyt megillető jubileumi jutalom.”"
        }
    ],
    "2011. évi XXIII. törvény": [
        {
            "needle": "helyébe az „az aktív korúak ellátására való jogosultság keretében megállapított pénzbeli ellátásban” szöveg lép.”",
            "replacement": "helyébe az „az aktív korúak ellátására való jogosultság keretében megállapított pénzbeli ellátásban” szöveg lép."
        }
    ],
    "2011. évi XXIX. törvény": [
        {
            "needle": "vonható vissza.”",
            "replacement": "vonható vissza."
        },
        {
            "needle": "alkalmazni.”",
            "needle_prev_lines": [
                "biztosítása érdekében – a 102/A. § (3) bekezdés a) pontját és a 102/B. § (1) és (2) bekezdését kell megfelelően"
            ],
            "replacement": "alkalmazni."
        },
        {
            "needle": "alkalmazható.”",
            "needle_prev_lines": [
                "megfelel az e §-ban foglaltaknak, a Hivatal határozatának jogerőre emelkedését követően a 102. §–102/E. § nem"
            ],
            "replacement": "alkalmazható."
        },
        {
            "needle": "(5) bekezdése, 178. § (7) bekezdése, 181. § (3) és (4) bekezdése, 183. §-a.”",
            "replacement": "(5) bekezdése, 178. § (7) bekezdése, 181. § (3) és (4) bekezdése, 183. §-a."
        },
        {
            "needle": "í) dönt a szállítási rendszerüzemeltető és a vertikálisan integrált földgázipari vállalkozás, valamint a 119/A. §",
            "replacement": "„í) dönt a szállítási rendszerüzemeltető és a vertikálisan integrált földgázipari vállalkozás, valamint a 119/A. §"
        }
    ],
    "2012. évi CCIX. törvény": [
        {
            "needle": "(11) Az Ogytv. 29. § (9) bekezdésében a „48. § (3)–(5)” szövegrész helyébe a „48. § (3)–(7)” szöveg lép”",
            "replacement": "(11) Az Ogytv. 29. § (9) bekezdésében a „48. § (3)–(5)” szövegrész helyébe a „48. § (3)–(7)” szöveg lép"
        }
    ],
    "2012. évi CCVIII. törvény": [
        {
            "needle": "szöveg lép.”",
            "needle_prev_lines": [
                "CXXVIII. törvény 17/A. § (1) bekezdésében a „18. § (7) bekezdése” szövegrész helyébe a „18. § (6) bekezdés b)–c) pontja”"
            ],
            "replacement": "szöveg lép."
        },
        {
            "needle": "szöveg lép.”",
            "replacement": "szöveg lép."
        }
    ],
    "2012. évi CCX. törvény": [
        {
            "needle": ",,(5) A 2. § (2) bekezdése és az 5. § (2) bekezdése szerint megkötött megállapodások, továbbá az 5. § (5) bekezdése",
            "replacement": "„(5) A 2. § (2) bekezdése és az 5. § (2) bekezdése szerint megkötött megállapodások, továbbá az 5. § (5) bekezdése"
        }
    ],
    "2012. évi CCXII. törvény": [
        {
            "needle": "szolgáltatásra jogosult személyt\" szöveg,",
            "replacement": "szolgáltatásra jogosult személyt” szöveg,"
        },
        {
            "needle": "5/A. § (1) Az 5. § (1) bekezdésben meghatározott szerződéseknek az 5. § (1) bekezdés alapján történő felmondása",
            "replacement": "„5/A. § (1) Az 5. § (1) bekezdésben meghatározott szerződéseknek az 5. § (1) bekezdés alapján történő felmondása"
        }
    ],
    "2012. évi CIV. törvény": [
        {
            "needle": "a) 7. § (4) bekezdésében a „jogszerűségét igazolni” szövegrész helyébe a jogszerűségéről nyilatkozni” szöveg,",
            "replacement": "a) 7. § (4) bekezdésében a „jogszerűségét igazolni” szövegrész helyébe a „jogszerűségéről nyilatkozni” szöveg,"
        },
        {
            "needle": "d) 27. § (4) bekezdés b) pont bd) alpontjában a „nevét (cégét), lakóhelyét (székhelyét) „ szövegrész helyébe a „nevét,",
            "replacement": "d) 27. § (4) bekezdés b) pont bd) alpontjában a „nevét (cégét), lakóhelyét (székhelyét) ” szövegrész helyébe a „nevét,"
        },
        {
            "needle": "tartalmazzák megfelelően a 44. §-ban foglalt adatközléshez szükséges adatokat „ szöveg,",
            "replacement": "tartalmazzák megfelelően a 44. §-ban foglalt adatközléshez szükséges adatokat ” szöveg,"
        },
        {
            "needle": "f) 39. § (1) bekezdésében a „(3) bekezdésének” szövegrész helyébe a „(2) bekezdésének „ szöveg,",
            "replacement": "f) 39. § (1) bekezdésében a „(3) bekezdésének” szövegrész helyébe a „(2) bekezdésének ” szöveg,"
        },
        {
            "needle": "befolyással” szöveg helyébe a „legalább többségi befolyással „ szöveg,",
            "replacement": "befolyással” szöveg helyébe a „legalább többségi befolyással ” szöveg,"
        },
        {
            "needle": "c) a Ctv. 53. § (1) bekezdésében a „ha a változás a cég tevékenységi körét érinti, illetve „ szövegrész,",
            "replacement": "c) a Ctv. 53. § (1) bekezdésében a „ha a változás a cég tevékenységi körét érinti, illetve ” szövegrész,"
        }
    ],
    "2012. évi CLII. törvény": [
        {
            "needle": "pénzügyi beszámolót, valamint teljesítményértékelést készít.\"",
            "replacement": "pénzügyi beszámolót, valamint teljesítményértékelést készít.”"
        }
    ],
    "2012. évi CLIV. törvény": [
        {
            "needle": "fenntartói jogok gyakorlására rendeletben kijelölt szervezet” szöveg, az „államháztartási törvényben\" szövegrész",
            "replacement": "fenntartói jogok gyakorlására rendeletben kijelölt szervezet” szöveg, az „államháztartási törvényben” szövegrész"
        },
        {
            "needle": "c) 40/A. § (1) bekezdésében a „termékenként\" szövegrész helyébe a „készítményenként\" szöveg,",
            "replacement": "c) 40/A. § (1) bekezdésében a „termékenként\" szövegrész helyébe a „készítményenként” szöveg,"
        },
        {
            "needle": "támogatásból le kell vonni a „36. § (1)–(2) és (4)–(4a), illetve 40/A. § (1) bekezdésében meghatározott fizetési",
            "replacement": "támogatásból le kell vonni a 36. § (1)–(2) és (4)–(4a), illetve 40/A. § (1) bekezdésében meghatározott fizetési"
        },
        {
            "needle": "c) 40/A. § (1) bekezdésében a „termékenként\" szövegrész helyébe a „készítményenként” szöveg,",
            "replacement": "c) 40/A. § (1) bekezdésében a „termékenként” szövegrész helyébe a „készítményenként” szöveg,"
        }
    ],
    "2012. évi CLVII. törvény": [
        {
            "needle": "a beruházó a feltárási engedély iránti kérelméhez csatolja a szerződést.\" szöveg,",
            "replacement": "a beruházó a feltárási engedély iránti kérelméhez csatolja a szerződést.” szöveg,"
        }
    ],
    "2012. évi CLXX. törvény": [
        {
            "needle": "hatóság megnevezéséről és címéről, valamint a jogorvoslat lehetőségéről vagy annak hiányáról.“",
            "replacement": "hatóság megnevezéséről és címéről, valamint a jogorvoslat lehetőségéről vagy annak hiányáról.”"
        }
    ],
    "2012. évi CLXXVIII. törvény": [
        {
            "needle": ",,c) a 124. § (1) bekezdésének c) pontjában és (4) bekezdésében említett esetekben igazoltan egészben vagy túlnyomó",
            "replacement": "„c) a 124. § (1) bekezdésének c) pontjában és (4) bekezdésében említett esetekben igazoltan egészben vagy túlnyomó"
        },
        {
            "needle": "a személygépkocsi osztály-jelzése: ”6”. Ha a személygépkocsi osztályjelzése a KöHÉM rendelet 2012. augusztus 15-ét",
            "replacement": "a személygépkocsi osztály-jelzése: „6”. Ha a személygépkocsi osztályjelzése a KöHÉM rendelet 2012. augusztus 15-ét"
        },
        {
            "needle": "17. tartozás: a magyar állami adó-, illetve vámhatóságnál – engedély nélkül – az előírt vagy a fizetési felszólításban",
            "replacement": "„17. tartozás: a magyar állami adó-, illetve vámhatóságnál – engedély nélkül – az előírt vagy a fizetési felszólításban"
        },
        {
            "needle": "benyújtásával egyidejűleg nem fizeti meg az eljárási illetéket” szöveg;”",
            "replacement": "benyújtásával egyidejűleg nem fizeti meg az eljárási illetéket” szöveg;"
        },
        {
            "needle": "eljárás igazgatási szolgáltatási díja esetén az 5 000 forintot.” szöveg;”",
            "replacement": "eljárás igazgatási szolgáltatási díja esetén az 5 000 forintot.” szöveg;"
        },
        {
            "needle": "15. 43/A. § b) pontjában az „éves szinten összesítve” és az „a tárgyévet követő augusztus 31-éig” szövegrész,”",
            "replacement": "15. 43/A. § b) pontjában az „éves szinten összesítve” és az „a tárgyévet követő augusztus 31-éig” szövegrész,"
        },
        {
            "needle": "b) 19. § (10) bekezdésében az „akkreditált” szövegrész.”",
            "replacement": "b) 19. § (10) bekezdésében az „akkreditált” szövegrész."
        }
    ],
    "2012. évi CXC. törvény": [
        {
            "needle": "„l) a közszolgáltatást ellátó szakmunkás szakmai továbbképzésére vonatkozó szabályokat.\"",
            "replacement": "„l) a közszolgáltatást ellátó szakmunkás szakmai továbbképzésére vonatkozó szabályokat.”"
        }
    ],
    "2012. évi CXCI. törvény": [
        {
            "needle": "hatályos anyagi jogi rendelkezések alkalmazandók.\"",
            "replacement": "hatályos anyagi jogi rendelkezések alkalmazandók.”"
        }
    ],
    "2012. évi CXCVI. törvény": [
        {
            "needle": "20. 78. § (4) bekezdés d) pontjában a „megfizetésének” szövegrész helyébe a megfizetésének, és” szöveg,",
            "replacement": "20. 78. § (4) bekezdés d) pontjában a „megfizetésének” szövegrész helyébe a „megfizetésének, és” szöveg,"
        }
    ],
    "2012. évi CXIX. törvény": [
        {
            "needle": "a 10 000 forintot;” szövegrész helyébe „a köztartozás összege eléri vagy meghaladja a 10 000 forintot;” szöveg lép.”",
            "replacement": "a 10 000 forintot;” szövegrész helyébe „a köztartozás összege eléri vagy meghaladja a 10 000 forintot;” szöveg lép."
        }
    ],
    "2012. évi CXVII. törvény": [
        {
            "needle": ",,(3) Az, akinek bírói szolgálati jogviszonya a Bjt. 90. § ha) pontja szerinti rá irányadó öregségi nyugdíjkorhatár betöltése",
            "replacement": "„(3) Az, akinek bírói szolgálati jogviszonya a Bjt. 90. § ha) pontja szerinti rá irányadó öregségi nyugdíjkorhatár betöltése"
        }
    ],
    "2012. évi CXXII. törvény": [
        {
            "needle": "(a továbbiakban mint ”Szerződő Felek”, és külön mint „Szerződő Fél”);",
            "replacement": "(a továbbiakban mint „Szerződő Felek”, és külön mint „Szerződő Fél”);"
        }
    ],
    "2012. évi LXI. törvény": [
        {
            "needle": "„ , illetőleg” szövegrész helyébe az „és a” szöveg, a „Magyar Országos Levéltárnak” szövegrész helyébe a ”Magyar",
            "replacement": "„ , illetőleg” szövegrész helyébe az „és a” szöveg, a „Magyar Országos Levéltárnak” szövegrész helyébe a „Magyar"
        }
    ],
    "2012. évi LXXIV. törvény": [
        {
            "needle": "„5. § (1) A géntechnológiai hatóság az engedély iránti kérelmet a géntechnológiai testület véleményére figyelemmel",
            "replacement": "5. § (1) A géntechnológiai hatóság az engedély iránti kérelmet a géntechnológiai testület véleményére figyelemmel"
        }
    ],
    "2012. évi LXXVI. törvény": [
        {
            "needle": ",,(9) Az ingatlan-nyilvántartásról szóló 1997. évi CXLI. törvény módosításáról szóló 2005. évi CXXII. törvény erejénél",
            "replacement": "„(9) Az ingatlan-nyilvántartásról szóló 1997. évi CXLI. törvény módosításáról szóló 2005. évi CXXII. törvény erejénél"
        },
        {
            "needle": ",,(3) A (2) bekezdés alapján tulajdonba adott ingatlanokon fennálló elidegenítési és terhelési tilalmat az ingatlan",
            "replacement": "„(3) A (2) bekezdés alapján tulajdonba adott ingatlanokon fennálló elidegenítési és terhelési tilalmat az ingatlan"
        }
    ],
    "2012. évi LXXXIV. törvény": [
        {
            "needle": "szolgáltatás,’’",
            "replacement": "szolgáltatás,”"
        }
    ],
    "2012. évi V. törvény": [
        {
            "needle": "XXIII. törvény 30/A. § (2) bekezdése” szövegrész helyébe a közszolgálati tisztviselőkről szóló törvény” szöveg lép.",
            "replacement": "XXIII. törvény 30/A. § (2) bekezdése” szövegrész helyébe „a közszolgálati tisztviselőkről szóló törvény” szöveg lép."
        }
    ],
    "2012. évi XCII. törvény": [
        {
            "needle": "g) “Processing of personal data” (hereafter referred to as ”processing”) shall mean any operation or set of operations",
            "replacement": "g) “Processing of personal data” (hereafter referred to as “processing”) shall mean any operation or set of operations"
        }
    ],
    "2012. évi XCIII. törvény": [
        {
            "needle": "d) a 12/G. § (2) bekezdésében a „talajvédelmi szempontokra és” szövegrész helyébe a művelhetőségi, és",
            "replacement": "d) a 12/G. § (2) bekezdésében a „talajvédelmi szempontokra és” szövegrész helyébe a „művelhetőségi, és"
        },
        {
            "needle": "I. törvény 81. § (1) bekezdésében az „okmányiroda” szövegrész helyébe a ”fővárosi és megyei kormányhivatal járási",
            "replacement": "I. törvény 81. § (1) bekezdésében az „okmányiroda” szövegrész helyébe a „fővárosi és megyei kormányhivatal járási"
        },
        {
            "needle": "járási (fővárosi kerületi) hivatala\" szöveg lép.",
            "replacement": "járási (fővárosi kerületi) hivatala” szöveg lép."
        },
        {
            "needle": "megyei kormányhivatal járási (fővárosi kerületi) hivatalának (a továbbiakban: járási hivatal) szöveg,",
            "replacement": "megyei kormányhivatal járási (fővárosi kerületi) hivatalának (a továbbiakban: járási hivatal)” szöveg,"
        },
        {
            "needle": "b) 91. § (1) bekezdéséből „– a jegyző 90/A. §-on alapuló határozatának kivételével –\" szövegrész.",
            "replacement": "b) 91. § (1) bekezdéséből „– a jegyző 90/A. §-on alapuló határozatának kivételével –” szövegrész."
        },
        {
            "needle": "hivatal) szöveg, az 55. § (6) bekezdésében és 60. § (2) bekezdésében a „jegyző” szövegrész helyébe a „járási hivatal”",
            "replacement": "hivatal)” szöveg, az 55. § (6) bekezdésében és 60. § (2) bekezdésében a „jegyző” szövegrész helyébe a „járási hivatal”"
        }
    ],
    "2012. évi XVII. törvény": [
        {
            "needle": "helyébe a „szervek” szöveg”, 84. § (3) bekezdésében az „irányító szerv által választott” szövegrész helyébe az „irányító",
            "replacement": "helyébe a „szervek” szöveg, 84. § (3) bekezdésében az „irányító szerv által választott” szövegrész helyébe az „irányító"
        }
    ],
    "2013. évi CCLII. törvény": [
        {
            "needle": "(4) A 6:198. § (3) bekezdése a következő szöveggel lép hatályba:",
            "replacement": "(4) A Ptk. 6:198. § (3) bekezdése a következő szöveggel lép hatályba:"
        },
        {
            "needle": ",,(1) Az egyesület jogutód nélküli megszűnése esetén a hitelezők követeléseinek kiegyenlítése után fennmaradó",
            "replacement": "„(1) Az egyesület jogutód nélküli megszűnése esetén a hitelezők követeléseinek kiegyenlítése után fennmaradó"
        },
        {
            "needle": ",,(3) A nyilvántartó bíróság jogszabályban meghatározott szervezetnek juttatja a vagyont, ha az alapító okirat, vagy",
            "replacement": "„(3) A nyilvántartó bíróság jogszabályban meghatározott szervezetnek juttatja a vagyont, ha az alapító okirat, vagy"
        }
    ],
    "2015. évi CIV. törvény": [
        {
            "needle": "„Felhatalmazás",
            "replacement": "Felhatalmazás"
        },
        {
            "needle": "28. § Felhatalmazást kap a Kormány, hogy e törvény alapján",
            "replacement": "„28. § Felhatalmazást kap a Kormány, hogy e törvény alapján"
        }
    ],
    "2016. évi CLXXIX. törvény": [
        {
            "needle": "tizenöt nappal követő időpontra hívják össze.”",
            "replacement": "tizenöt nappal követő időpontra hívják össze."
        }
    ],
    "2016. évi CLXXXIV. törvény": [
        {
            "needle": "„143. § (1) Árvák kiegészítő támogatására jogosult az állomány elhunyt tagjának – ideértve a 224. § (3) bekezdése",
            "replacement": "143. § (1) Árvák kiegészítő támogatására jogosult az állomány elhunyt tagjának – ideértve a 224. § (3) bekezdése"
        },
        {
            "needle": "a) az önkéntes tartalékos katona hivatásos, szerződéses, honvéd tisztjelölt vagy honvéd altiszt-jelölt szolgálati",
            "replacement": "„a) az önkéntes tartalékos katona hivatásos, szerződéses, honvéd tisztjelölt vagy honvéd altiszt-jelölt szolgálati"
        }
    ],
    "2018. évi LI. törvény": [
        {
            "needle": "Maďarsko a Slovenská republika (ďalej len „zmluvné strany“),",
            "replacement": "Maďarsko a Slovenská republika (ďalej len „zmluvné strany”),"
        },
        {
            "needle": "slovenskej hraničnej čiary – hraničné úseky č. III., IV. a VIII. – 2013“, ktorý ako príloha tejto zmluvy tvorí jej",
            "replacement": "slovenskej hraničnej čiary – hraničné úseky č. III., IV. a VIII. – 2013”, ktorý ako príloha tejto zmluvy tvorí jej"
        },
        {
            "needle": "MAĎARSKO SLOVENSKÚ REPUBLIKU“",
            "replacement": "MAĎARSKO SLOVENSKÚ REPUBLIKU”"
        }
    ]
}
