# THIS FILE IS GENERATED BY A TOOL. PLEASE DO NOT MODIFY MANUALLY.

replacement_fixups = {
    "2010. évi CLIII. törvény": [
        {
            "needle": "a „15 munkanapon belül” szöveg, valamint 140. § (6) bekezdésében a 8 munkanapon belül” szövegrész helyébe",
            "replacement": "a „15 munkanapon belül” szöveg, valamint 140. § (6) bekezdésében a „8 munkanapon belül” szövegrész helyébe"
        }
    ],
    "2010. évi CLIX. törvény": [
        {
            "needle": "résztvevő a rendszerüzemeltető számára ismert;”",
            "replacement": "résztvevő a rendszerüzemeltető számára ismert;"
        }
    ],
    "2010. évi CLXXII. törvény": [
        {
            "needle": "tesz közzé.”",
            "replacement": "tesz közzé."
        },
        {
            "needle": "vonatokról, valamint vasúti állomásról és megállóhelyről a szolgáltató a honlapján tájékoztatást tesz közzé.”",
            "replacement": "vonatokról, valamint vasúti állomásról és megállóhelyről a szolgáltató a honlapján tájékoztatást tesz közzé."
        },
        {
            "needle": "szövegrész helyébe a „miniszterrel egyetértésben” szöveg, 74. § (1) bekezdés m) pontjában az „is – „ szövegrész",
            "replacement": "szövegrész helyébe a „miniszterrel egyetértésben” szöveg, 74. § (1) bekezdés m) pontjában az „is – ” szövegrész"
        },
        {
            "needle": "helyébe az – egyetértésben” szöveg, 74. § (2) bekezdés k) és l) pontjában a „miniszter az” szövegrész helyébe",
            "replacement": "helyébe az „– egyetértésben” szöveg, 74. § (2) bekezdés k) és l) pontjában a „miniszter az” szövegrész helyébe"
        }
    ],
    "2010. évi CLXXIII. törvény": [
        {
            "needle": "a „jelölt tag” szövegrész helyébe a „kinevezett tag” szöveg lép.”",
            "replacement": "a „jelölt tag” szövegrész helyébe a „kinevezett tag” szöveg lép."
        }
    ],
    "2010. évi CLXXX. törvény": [
        {
            "needle": "jogosult, ha a szerződésében a teljes önkéntesség tényét nem rögzítette.”",
            "replacement": "jogosult, ha a szerződésében a teljes önkéntesség tényét nem rögzítette."
        }
    ],
    "2010. évi CLXXXIII. törvény": [
        {
            "needle": "(4) E törvény 67. §-a, 165. § (2) bekezdés e) és f) pontja 2011. szeptember 1-jén lép hatályba.”",
            "replacement": "(4) E törvény 67. §-a, 165. § (2) bekezdés e) és f) pontja 2011. szeptember 1-jén lép hatályba."
        }
    ],
    "2010. évi CXLVIII. törvény": [
        {
            "needle": "(7) bekezdésében a „huszonkét” szövegrész helyébe a „harminc” szöveg lép.”",
            "replacement": "(7) bekezdésében a „huszonkét” szövegrész helyébe a „harminc” szöveg lép."
        }
    ],
    "2011. évi CCIX. törvény": [
        {
            "needle": "alkalmazni.”",
            "replacement": "alkalmazni.””"
        }
    ],
    "2011. évi CCVII. törvény": [
        {
            "needle": "g) 2. számú melléklet 10. pontja.”",
            "replacement": "g) 2. számú melléklet 10. pontja."
        }
    ],
    "2011. évi CLIV. törvény": [
        {
            "needle": "g) 92. § (3) bekezdés első mondatában az ”, illetve a megyei önkormányzat a településen, illetve a megyében”",
            "replacement": "g) 92. § (3) bekezdés első mondatában az „, illetve a megyei önkormányzat a településen, illetve a megyében”"
        },
        {
            "needle": "j) 89/B. § (7) bekezdésében a „megyei önkormányzat” szövegrész helyébe a Kormány általános hatáskörű területi",
            "replacement": "j) 89/B. § (7) bekezdésében a „megyei önkormányzat” szövegrész helyébe a „Kormány általános hatáskörű területi"
        }
    ],
    "2011. évi CLXI. törvény": [
        {
            "needle": ",,A munkaköri kötelességeimet részrehajlás nélkül, lelkiismeretesen, kizárólag a jogszabályoknak megfelelően,",
            "replacement": "„A munkaköri kötelességeimet részrehajlás nélkül, lelkiismeretesen, kizárólag a jogszabályoknak megfelelően,"
        }
    ],
    "2011. évi CLXII. törvény": [
        {
            "needle": ",,Fogadom, hogy a rám bízott ügyeket tisztességes eljárásban, részrehajlás nélkül, lelkiismeretesen, kizárólag",
            "replacement": "„Fogadom, hogy a rám bízott ügyeket tisztességes eljárásban, részrehajlás nélkül, lelkiismeretesen, kizárólag"
        }
    ],
    "2011. évi CLXVI. törvény": [
        {
            "needle": "„(A kiadások fedezetét a következő bevételek képezik:",
            "replacement": "(A kiadások fedezetét a következő bevételek képezik:"
        }
    ],
    "2011. évi CLXX. törvény": [
        {
            "needle": "(2) Az 1–25. §, a 27. § és az 1. melléklet 2012. január 1-jén lép hatályba.”",
            "replacement": "(2) Az 1–25. §, a 27. § és az 1. melléklet 2012. január 1-jén lép hatályba."
        }
    ],
    "2011. évi CLXXII. törvény": [
        {
            "needle": "a bi) alpontjában a „Magyar Köztársaság” szövegrész helyébe a „Magyarország” szöveg lép.”",
            "replacement": "a bi) alpontjában a „Magyar Köztársaság” szövegrész helyébe a „Magyarország” szöveg lép."
        }
    ],
    "2011. évi CLXXIII. törvény": [
        {
            "needle": "„kihirdetésétől” szövegrész helyébe a „kézbesítésétől” szöveg lép.”",
            "replacement": "„kihirdetésétől” szövegrész helyébe a „kézbesítésétől” szöveg lép."
        }
    ],
    "2011. évi CLXXV. törvény": [
        {
            "needle": "„ „45. § A Tao tv. a következő 29/Q. §-sal egészül ki:",
            "replacement": "„45. § A Tao tv. a következő 29/Q. §-sal egészül ki:"
        },
        {
            "needle": "szöveg lép .",
            "replacement": "szöveg lép .”"
        }
    ],
    "2011. évi CLXXVI. törvény": [
        {
            "needle": "(3) bekezdésében foglaltakon túl – „ szövegrész helyébe az „– az 5/A. § (3) bekezdésében és (11) bekezdésének",
            "replacement": "(3) bekezdésében foglaltakon túl – ” szövegrész helyébe az „– az 5/A. § (3) bekezdésében és (11) bekezdésének"
        },
        {
            "needle": "g) 4. számú melléklete.”",
            "replacement": "g) 4. számú melléklete."
        }
    ],
    "2011. évi CLXXXIV. törvény": [
        {
            "needle": "helyébe a ”kormányzati szolgálati, közszolgálati, vagy” szöveg,",
            "replacement": "helyébe a „kormányzati szolgálati, közszolgálati, vagy” szöveg,"
        }
    ],
    "2011. évi CV. törvény": [
        {
            "needle": "b) ha egyenlőtlen munkaidő-beosztásban kíván dolgozni, a munkaidő-beosztásra vonatkozó javaslatáról.”",
            "replacement": "b) ha egyenlőtlen munkaidő-beosztásban kíván dolgozni, a munkaidő-beosztásra vonatkozó javaslatáról."
        },
        {
            "needle": "történő foglalkoztatásnak a Módtv. hatálybalépését követően ledolgozott időtartama tekintetében kell alkalmazni.”",
            "replacement": "történő foglalkoztatásnak a Módtv. hatálybalépését követően ledolgozott időtartama tekintetében kell alkalmazni."
        }
    ],
    "2011. évi CVI. törvény": [
        {
            "needle": "(6) bekezdésében, valamint 37/C. § (8) bekezdés a) pontjában a ”bérpótló juttatásra” szövegrész helyébe",
            "replacement": "(6) bekezdésében, valamint 37/C. § (8) bekezdés a) pontjában a „bérpótló juttatásra” szövegrész helyébe"
        }
    ],
    "2011. évi CVII. törvény": [
        {
            "needle": "szempontjából nem megfelelő, akkor annak üzemben tartóját terhelik.”",
            "replacement": "szempontjából nem megfelelő, akkor annak üzemben tartóját terhelik."
        },
        {
            "needle": "49/a. Helymeghatározási szolgáltatás: olyan kapcsolódó szolgáltatás, amelyet az előfizető vagy felhasználó",
            "replacement": "„49/a. Helymeghatározási szolgáltatás: olyan kapcsolódó szolgáltatás, amelyet az előfizető vagy felhasználó"
        },
        {
            "needle": "szöveg,”, a 31. § (3) bekezdésében „Az (1)–(2) bekezdésben” szövegrész helyébe „A (2) bekezdésben” szöveg, a 33. §",
            "replacement": "szöveg, a 31. § (3) bekezdésében „Az (1)–(2) bekezdésben” szövegrész helyébe „A (2) bekezdésben” szöveg, a 33. §"
        },
        {
            "needle": "rendelkezések alkalmazandók.”",
            "replacement": "rendelkezések alkalmazandók."
        }
    ],
    "2011. évi CXCIII. törvény": [
        {
            "needle": "megszüntetéséről a befektetési alapkezelő dönt, amelynek során az ”IL” sorozatjelű befektetési jegyeket az alap",
            "replacement": "megszüntetéséről a befektetési alapkezelő dönt, amelynek során az „IL” sorozatjelű befektetési jegyeket az alap"
        },
        {
            "needle": "a „2011. december 31-ig” szövegrész helyébe a „2012. június 30-ig” szöveg lép.”",
            "replacement": "a „2011. december 31-ig” szövegrész helyébe a „2012. június 30-ig” szöveg lép."
        },
        {
            "needle": "hatósági felügyeleti,” szöveg lép.”",
            "replacement": "hatósági felügyeleti,” szöveg lép."
        },
        {
            "needle": "valamint e szolgáltatások fedezetéről szóló 1997. évi LXXX. törvény 3. § (2) bekezdése szerinti kötelezettségét.”",
            "replacement": "valamint e szolgáltatások fedezetéről szóló 1997. évi LXXX. törvény 3. § (2) bekezdése szerinti kötelezettségét.””"
        }
    ],
    "2011. évi CXCVII. törvény": [
        {
            "needle": "bocsátott vagyonból.”",
            "needle_prev_lines": [
                "biztosíték teljesítéséért a vezetőtől való behajthatatlanság esetén kezesként felel. A külföldi székhelyű vállalkozás",
                "az említett kezesi kötelezettségéből eredő fizetési kötelezettségét nem teljesítheti a fióktelepe rendelkezésére"
            ],
            "replacement": "bocsátott vagyonból."
        },
        {
            "needle": "(8) bekezdése.”",
            "replacement": "(8) bekezdése."
        }
    ],
    "2011. évi CXLIV. törvény": [
        {
            "needle": "Ireland signed at Budapest on 28th November 1977 (”the prior Convention”) shall cease to be effective from the dates",
            "replacement": "Ireland signed at Budapest on 28th November 1977 („the prior Convention”) shall cease to be effective from the dates"
        }
    ],
    "2011. évi CXLV. törvény": [
        {
            "needle": "\"C O N V E N T I O N",
            "replacement": "„C O N V E N T I O N"
        }
    ],
    "2011. évi CXXV. törvény": [
        {
            "needle": "a 2012. január–március tárgynegyedévre kell alkalmazni.”",
            "needle_prev_lines": [
                "CXXV. törvénnyel megállapított 33. § (2), (3), (6) bekezdéseit 2012. január 1. napjától és első alkalommal"
            ],
            "replacement": "a 2012. január–március tárgynegyedévre kell alkalmazni."
        }
    ],
    "2011. évi CXXXVI. törvény": [
        {
            "needle": "2. § Az Országgyűlés Szigetvár városnak a „Leghősiesebb Város” ( „Civitas Invicta\") címet adományozza.",
            "replacement": "2. § Az Országgyűlés Szigetvár városnak a „Leghősiesebb Város” ( „Civitas Invicta”) címet adományozza."
        }
    ],
    "2011. évi LIX. törvény": [
        {
            "needle": "szövegrész.”",
            "replacement": "szövegrész."
        },
        {
            "needle": "(17) A VET. 171/A. §-a 2012. szeptember 30-án hatályát veszti.”",
            "replacement": "(17) A VET. 171/A. §-a 2012. szeptember 30-án hatályát veszti."
        }
    ],
    "2011. évi LXV. törvény": [
        {
            "needle": "Szlovén Köztársaság A 20. cikkben kijelölt szolgálatok",
            "replacement": "Szlovén Köztársaság A 20. cikkben kijelölt szolgálatok”"
        }
    ],
    "2011. évi LXXXIV. törvény": [
        {
            "needle": "a silent partner ( „stiller Gesellschafter“) from his participation as such, or from a loan with an interest rate linked to",
            "replacement": "a silent partner ( „stiller Gesellschafter”) from his participation as such, or from a loan with an interest rate linked to"
        },
        {
            "needle": "borrower’s profit ( „partiarisches Darlehen“) or from profit sharing bonds ( „Gewinnobligationen“) within",
            "replacement": "borrower’s profit ( „partiarisches Darlehen”) or from profit sharing bonds ( „Gewinnobligationen”) within"
        }
    ],
    "2011. évi LXXXVI. törvény": [
        {
            "needle": "(5) E törvény 2012. május 2-án hatályát veszti.”",
            "replacement": "(5) E törvény 2012. május 2-án hatályát veszti."
        }
    ],
    "2011. évi XCVI. törvény": [
        {
            "needle": "35. § (1) A MódTv. 82. § (1) bekezdésében a „2010. október 31.” szövegrész helyébe a 2011. április 30.” szöveg lép.",
            "replacement": "35. § (1) A MódTv. 82. § (1) bekezdésében a „2010. október 31.” szövegrész helyébe a „2011. április 30.” szöveg lép."
        },
        {
            "needle": "Zsigmond Király Főiskola, Budapest\"",
            "replacement": "Zsigmond Király Főiskola, Budapest”"
        }
    ],
    "2011. évi XLVI. törvény": [
        {
            "needle": "kifizetett bevétel, illetve a jogviszony megszűnésekor a magánszemélyt megillető jubileumi jutalom.\"",
            "replacement": "kifizetett bevétel, illetve a jogviszony megszűnésekor a magánszemélyt megillető jubileumi jutalom.”"
        }
    ],
    "2011. évi XXIII. törvény": [
        {
            "needle": "helyébe az „az aktív korúak ellátására való jogosultság keretében megállapított pénzbeli ellátásban” szöveg lép.”",
            "replacement": "helyébe az „az aktív korúak ellátására való jogosultság keretében megállapított pénzbeli ellátásban” szöveg lép."
        }
    ],
    "2011. évi XXIX. törvény": [
        {
            "needle": "vonható vissza.”",
            "replacement": "vonható vissza."
        },
        {
            "needle": "alkalmazni.”",
            "needle_prev_lines": [
                "biztosítása érdekében – a 102/A. § (3) bekezdés a) pontját és a 102/B. § (1) és (2) bekezdését kell megfelelően"
            ],
            "replacement": "alkalmazni."
        },
        {
            "needle": "alkalmazható.”",
            "needle_prev_lines": [
                "megfelel az e §-ban foglaltaknak, a Hivatal határozatának jogerőre emelkedését követően a 102. §–102/E. § nem"
            ],
            "replacement": "alkalmazható."
        },
        {
            "needle": "(5) bekezdése, 178. § (7) bekezdése, 181. § (3) és (4) bekezdése, 183. §-a.”",
            "replacement": "(5) bekezdése, 178. § (7) bekezdése, 181. § (3) és (4) bekezdése, 183. §-a."
        },
        {
            "needle": "í) dönt a szállítási rendszerüzemeltető és a vertikálisan integrált földgázipari vállalkozás, valamint a 119/A. §",
            "replacement": "„í) dönt a szállítási rendszerüzemeltető és a vertikálisan integrált földgázipari vállalkozás, valamint a 119/A. §"
        }
    ],
    "2012. évi CCIX. törvény": [
        {
            "needle": "(11) Az Ogytv. 29. § (9) bekezdésében a „48. § (3)–(5)” szövegrész helyébe a „48. § (3)–(7)” szöveg lép”",
            "replacement": "(11) Az Ogytv. 29. § (9) bekezdésében a „48. § (3)–(5)” szövegrész helyébe a „48. § (3)–(7)” szöveg lép"
        }
    ],
    "2012. évi CCVIII. törvény": [
        {
            "needle": "szöveg lép.”",
            "needle_prev_lines": [
                "CXXVIII. törvény 17/A. § (1) bekezdésében a „18. § (7) bekezdése” szövegrész helyébe a „18. § (6) bekezdés b)–c) pontja”"
            ],
            "replacement": "szöveg lép."
        },
        {
            "needle": "szöveg lép.”",
            "replacement": "szöveg lép."
        }
    ],
    "2012. évi CCX. törvény": [
        {
            "needle": ",,(5) A 2. § (2) bekezdése és az 5. § (2) bekezdése szerint megkötött megállapodások, továbbá az 5. § (5) bekezdése",
            "replacement": "„(5) A 2. § (2) bekezdése és az 5. § (2) bekezdése szerint megkötött megállapodások, továbbá az 5. § (5) bekezdése"
        }
    ],
    "2012. évi CCXII. törvény": [
        {
            "needle": "szolgáltatásra jogosult személyt\" szöveg,",
            "replacement": "szolgáltatásra jogosult személyt” szöveg,"
        },
        {
            "needle": "5/A. § (1) Az 5. § (1) bekezdésben meghatározott szerződéseknek az 5. § (1) bekezdés alapján történő felmondása",
            "replacement": "„5/A. § (1) Az 5. § (1) bekezdésben meghatározott szerződéseknek az 5. § (1) bekezdés alapján történő felmondása"
        }
    ],
    "2012. évi CIV. törvény": [
        {
            "needle": "a) 7. § (4) bekezdésében a „jogszerűségét igazolni” szövegrész helyébe a jogszerűségéről nyilatkozni” szöveg,",
            "replacement": "a) 7. § (4) bekezdésében a „jogszerűségét igazolni” szövegrész helyébe a „jogszerűségéről nyilatkozni” szöveg,"
        },
        {
            "needle": "d) 27. § (4) bekezdés b) pont bd) alpontjában a „nevét (cégét), lakóhelyét (székhelyét) „ szövegrész helyébe a „nevét,",
            "replacement": "d) 27. § (4) bekezdés b) pont bd) alpontjában a „nevét (cégét), lakóhelyét (székhelyét) ” szövegrész helyébe a „nevét,"
        },
        {
            "needle": "tartalmazzák megfelelően a 44. §-ban foglalt adatközléshez szükséges adatokat „ szöveg,",
            "replacement": "tartalmazzák megfelelően a 44. §-ban foglalt adatközléshez szükséges adatokat ” szöveg,"
        },
        {
            "needle": "f) 39. § (1) bekezdésében a „(3) bekezdésének” szövegrész helyébe a „(2) bekezdésének „ szöveg,",
            "replacement": "f) 39. § (1) bekezdésében a „(3) bekezdésének” szövegrész helyébe a „(2) bekezdésének ” szöveg,"
        },
        {
            "needle": "befolyással” szöveg helyébe a „legalább többségi befolyással „ szöveg,",
            "replacement": "befolyással” szöveg helyébe a „legalább többségi befolyással ” szöveg,"
        },
        {
            "needle": "c) a Ctv. 53. § (1) bekezdésében a „ha a változás a cég tevékenységi körét érinti, illetve „ szövegrész,",
            "replacement": "c) a Ctv. 53. § (1) bekezdésében a „ha a változás a cég tevékenységi körét érinti, illetve ” szövegrész,"
        }
    ],
    "2012. évi CLII. törvény": [
        {
            "needle": "pénzügyi beszámolót, valamint teljesítményértékelést készít.\"",
            "replacement": "pénzügyi beszámolót, valamint teljesítményértékelést készít.”"
        }
    ],
    "2012. évi CLIV. törvény": [
        {
            "needle": "fenntartói jogok gyakorlására rendeletben kijelölt szervezet” szöveg, az „államháztartási törvényben\" szövegrész",
            "replacement": "fenntartói jogok gyakorlására rendeletben kijelölt szervezet” szöveg, az „államháztartási törvényben” szövegrész"
        },
        {
            "needle": "c) 40/A. § (1) bekezdésében a „termékenként\" szövegrész helyébe a „készítményenként\" szöveg,",
            "replacement": "c) 40/A. § (1) bekezdésében a „termékenként\" szövegrész helyébe a „készítményenként” szöveg,"
        },
        {
            "needle": "támogatásból le kell vonni a „36. § (1)–(2) és (4)–(4a), illetve 40/A. § (1) bekezdésében meghatározott fizetési",
            "replacement": "támogatásból le kell vonni a 36. § (1)–(2) és (4)–(4a), illetve 40/A. § (1) bekezdésében meghatározott fizetési"
        },
        {
            "needle": "c) 40/A. § (1) bekezdésében a „termékenként\" szövegrész helyébe a „készítményenként” szöveg,",
            "replacement": "c) 40/A. § (1) bekezdésében a „termékenként” szövegrész helyébe a „készítményenként” szöveg,"
        }
    ],
    "2012. évi CLVII. törvény": [
        {
            "needle": "a beruházó a feltárási engedély iránti kérelméhez csatolja a szerződést.\" szöveg,",
            "replacement": "a beruházó a feltárási engedély iránti kérelméhez csatolja a szerződést.” szöveg,"
        }
    ],
    "2012. évi CLXX. törvény": [
        {
            "needle": "hatóság megnevezéséről és címéről, valamint a jogorvoslat lehetőségéről vagy annak hiányáról.“",
            "replacement": "hatóság megnevezéséről és címéről, valamint a jogorvoslat lehetőségéről vagy annak hiányáról.”"
        }
    ],
    "2012. évi CLXXVIII. törvény": [
        {
            "needle": ",,c) a 124. § (1) bekezdésének c) pontjában és (4) bekezdésében említett esetekben igazoltan egészben vagy túlnyomó",
            "replacement": "„c) a 124. § (1) bekezdésének c) pontjában és (4) bekezdésében említett esetekben igazoltan egészben vagy túlnyomó"
        },
        {
            "needle": "a személygépkocsi osztály-jelzése: ”6”. Ha a személygépkocsi osztályjelzése a KöHÉM rendelet 2012. augusztus 15-ét",
            "replacement": "a személygépkocsi osztály-jelzése: „6”. Ha a személygépkocsi osztályjelzése a KöHÉM rendelet 2012. augusztus 15-ét"
        },
        {
            "needle": "17. tartozás: a magyar állami adó-, illetve vámhatóságnál – engedély nélkül – az előírt vagy a fizetési felszólításban",
            "replacement": "„17. tartozás: a magyar állami adó-, illetve vámhatóságnál – engedély nélkül – az előírt vagy a fizetési felszólításban"
        },
        {
            "needle": "benyújtásával egyidejűleg nem fizeti meg az eljárási illetéket” szöveg;”",
            "replacement": "benyújtásával egyidejűleg nem fizeti meg az eljárási illetéket” szöveg;"
        },
        {
            "needle": "eljárás igazgatási szolgáltatási díja esetén az 5 000 forintot.” szöveg;”",
            "replacement": "eljárás igazgatási szolgáltatási díja esetén az 5 000 forintot.” szöveg;"
        },
        {
            "needle": "15. 43/A. § b) pontjában az „éves szinten összesítve” és az „a tárgyévet követő augusztus 31-éig” szövegrész,”",
            "replacement": "15. 43/A. § b) pontjában az „éves szinten összesítve” és az „a tárgyévet követő augusztus 31-éig” szövegrész,"
        },
        {
            "needle": "b) 19. § (10) bekezdésében az „akkreditált” szövegrész.”",
            "replacement": "b) 19. § (10) bekezdésében az „akkreditált” szövegrész."
        }
    ],
    "2012. évi CXC. törvény": [
        {
            "needle": "„l) a közszolgáltatást ellátó szakmunkás szakmai továbbképzésére vonatkozó szabályokat.\"",
            "replacement": "„l) a közszolgáltatást ellátó szakmunkás szakmai továbbképzésére vonatkozó szabályokat.”"
        }
    ],
    "2012. évi CXCI. törvény": [
        {
            "needle": "hatályos anyagi jogi rendelkezések alkalmazandók.\"",
            "replacement": "hatályos anyagi jogi rendelkezések alkalmazandók.”"
        }
    ],
    "2012. évi CXCVI. törvény": [
        {
            "needle": "20. 78. § (4) bekezdés d) pontjában a „megfizetésének” szövegrész helyébe a megfizetésének, és” szöveg,",
            "replacement": "20. 78. § (4) bekezdés d) pontjában a „megfizetésének” szövegrész helyébe a „megfizetésének, és” szöveg,"
        }
    ],
    "2012. évi CXIX. törvény": [
        {
            "needle": "a 10 000 forintot;” szövegrész helyébe „a köztartozás összege eléri vagy meghaladja a 10 000 forintot;” szöveg lép.”",
            "replacement": "a 10 000 forintot;” szövegrész helyébe „a köztartozás összege eléri vagy meghaladja a 10 000 forintot;” szöveg lép."
        }
    ],
    "2012. évi CXVII. törvény": [
        {
            "needle": ",,(3) Az, akinek bírói szolgálati jogviszonya a Bjt. 90. § ha) pontja szerinti rá irányadó öregségi nyugdíjkorhatár betöltése",
            "replacement": "„(3) Az, akinek bírói szolgálati jogviszonya a Bjt. 90. § ha) pontja szerinti rá irányadó öregségi nyugdíjkorhatár betöltése"
        }
    ],
    "2012. évi CXXII. törvény": [
        {
            "needle": "(a továbbiakban mint ”Szerződő Felek”, és külön mint „Szerződő Fél”);",
            "replacement": "(a továbbiakban mint „Szerződő Felek”, és külön mint „Szerződő Fél”);"
        }
    ],
    "2012. évi LXI. törvény": [
        {
            "needle": "„ , illetőleg” szövegrész helyébe az „és a” szöveg, a „Magyar Országos Levéltárnak” szövegrész helyébe a ”Magyar",
            "replacement": "„ , illetőleg” szövegrész helyébe az „és a” szöveg, a „Magyar Országos Levéltárnak” szövegrész helyébe a „Magyar"
        }
    ],
    "2012. évi LXXIV. törvény": [
        {
            "needle": "„5. § (1) A géntechnológiai hatóság az engedély iránti kérelmet a géntechnológiai testület véleményére figyelemmel",
            "replacement": "5. § (1) A géntechnológiai hatóság az engedély iránti kérelmet a géntechnológiai testület véleményére figyelemmel"
        }
    ],
    "2012. évi LXXVI. törvény": [
        {
            "needle": ",,(9) Az ingatlan-nyilvántartásról szóló 1997. évi CXLI. törvény módosításáról szóló 2005. évi CXXII. törvény erejénél",
            "replacement": "„(9) Az ingatlan-nyilvántartásról szóló 1997. évi CXLI. törvény módosításáról szóló 2005. évi CXXII. törvény erejénél"
        },
        {
            "needle": ",,(3) A (2) bekezdés alapján tulajdonba adott ingatlanokon fennálló elidegenítési és terhelési tilalmat az ingatlan",
            "replacement": "„(3) A (2) bekezdés alapján tulajdonba adott ingatlanokon fennálló elidegenítési és terhelési tilalmat az ingatlan"
        }
    ],
    "2012. évi LXXXIV. törvény": [
        {
            "needle": "szolgáltatás,’’",
            "replacement": "szolgáltatás,”"
        }
    ],
    "2012. évi V. törvény": [
        {
            "needle": "XXIII. törvény 30/A. § (2) bekezdése” szövegrész helyébe a közszolgálati tisztviselőkről szóló törvény” szöveg lép.",
            "replacement": "XXIII. törvény 30/A. § (2) bekezdése” szövegrész helyébe „a közszolgálati tisztviselőkről szóló törvény” szöveg lép."
        }
    ],
    "2012. évi XCII. törvény": [
        {
            "needle": "g) “Processing of personal data” (hereafter referred to as ”processing”) shall mean any operation or set of operations",
            "replacement": "g) “Processing of personal data” (hereafter referred to as “processing”) shall mean any operation or set of operations"
        }
    ],
    "2012. évi XCIII. törvény": [
        {
            "needle": "d) a 12/G. § (2) bekezdésében a „talajvédelmi szempontokra és” szövegrész helyébe a művelhetőségi, és",
            "replacement": "d) a 12/G. § (2) bekezdésében a „talajvédelmi szempontokra és” szövegrész helyébe a „művelhetőségi, és"
        },
        {
            "needle": "I. törvény 81. § (1) bekezdésében az „okmányiroda” szövegrész helyébe a ”fővárosi és megyei kormányhivatal járási",
            "replacement": "I. törvény 81. § (1) bekezdésében az „okmányiroda” szövegrész helyébe a „fővárosi és megyei kormányhivatal járási"
        },
        {
            "needle": "járási (fővárosi kerületi) hivatala\" szöveg lép.",
            "replacement": "járási (fővárosi kerületi) hivatala” szöveg lép."
        },
        {
            "needle": "megyei kormányhivatal járási (fővárosi kerületi) hivatalának (a továbbiakban: járási hivatal) szöveg,",
            "replacement": "megyei kormányhivatal járási (fővárosi kerületi) hivatalának (a továbbiakban: járási hivatal)” szöveg,"
        },
        {
            "needle": "b) 91. § (1) bekezdéséből „– a jegyző 90/A. §-on alapuló határozatának kivételével –\" szövegrész.",
            "replacement": "b) 91. § (1) bekezdéséből „– a jegyző 90/A. §-on alapuló határozatának kivételével –” szövegrész."
        },
        {
            "needle": "hivatal) szöveg, az 55. § (6) bekezdésében és 60. § (2) bekezdésében a „jegyző” szövegrész helyébe a „járási hivatal”",
            "replacement": "hivatal)” szöveg, az 55. § (6) bekezdésében és 60. § (2) bekezdésében a „jegyző” szövegrész helyébe a „járási hivatal”"
        }
    ],
    "2012. évi XVII. törvény": [
        {
            "needle": "helyébe a „szervek” szöveg”, 84. § (3) bekezdésében az „irányító szerv által választott” szövegrész helyébe az „irányító",
            "replacement": "helyébe a „szervek” szöveg, 84. § (3) bekezdésében az „irányító szerv által választott” szövegrész helyébe az „irányító"
        }
    ],
    "2013. évi CC. törvény": [
        {
            "needle": "tartalmazza az összeférhetetlenség megszüntetésére vonatkozó felszólítást is.”",
            "replacement": "tartalmazza az összeférhetetlenség megszüntetésére vonatkozó felszólítást is."
        }
    ],
    "2013. évi CCL. törvény": [
        {
            "needle": ",,(7) A közigazgatási hatósági eljárás és szolgáltatás általános szabályairól szóló törvény hatósági bizonyítvány",
            "replacement": "„(7) A közigazgatási hatósági eljárás és szolgáltatás általános szabályairól szóló törvény hatósági bizonyítvány"
        },
        {
            "needle": "n) 75. § (4) bekezdésében az ,,a (2)–(3) bekezdések szerint” szövegrész helyébe az ,,a (2)–(2a) bekezdés szerint”",
            "replacement": "n) 75. § (4) bekezdésében az „a (2)–(3) bekezdések szerint” szövegrész helyébe az „a (2)–(2a) bekezdés szerint”"
        },
        {
            "needle": "e) 38. § (1) bekezdés a) pontjában a „feladatait és hatáskörét” szövegrész helyébe a feladatait, hatáskörét és",
            "replacement": "e) 38. § (1) bekezdés a) pontjában a „feladatait és hatáskörét” szövegrész helyébe a „feladatait, hatáskörét és"
        },
        {
            "needle": "(2) A Hktv. 40. § (4) bekezdésében a ,,térítésmentesen” szövegrész helyébe a ,,térítésmentesen, valamint az elektronikus",
            "replacement": "(2) A Hktv. 40. § (4) bekezdésében a „térítésmentesen” szövegrész helyébe a „térítésmentesen, valamint az elektronikus"
        }
    ],
    "2013. évi CCLII. törvény": [
        {
            "needle": "(4) A 6:198. § (3) bekezdése a következő szöveggel lép hatályba:",
            "replacement": "(4) A Ptk. 6:198. § (3) bekezdése a következő szöveggel lép hatályba:"
        },
        {
            "needle": ",,(1) Az egyesület jogutód nélküli megszűnése esetén a hitelezők követeléseinek kiegyenlítése után fennmaradó",
            "replacement": "„(1) Az egyesület jogutód nélküli megszűnése esetén a hitelezők követeléseinek kiegyenlítése után fennmaradó"
        },
        {
            "needle": ",,(3) A nyilvántartó bíróság jogszabályban meghatározott szervezetnek juttatja a vagyont, ha az alapító okirat, vagy",
            "replacement": "„(3) A nyilvántartó bíróság jogszabályban meghatározott szervezetnek juttatja a vagyont, ha az alapító okirat, vagy"
        }
    ],
    "2013. évi CCXLIII. törvény": [
        {
            "needle": "p) 3. melléklet 4. sorában a „kollégiumvezető-helyettese” szövegrész helyébe a kollégiumvezető-helyettese és",
            "replacement": "p) 3. melléklet 4. sorában a „kollégiumvezető-helyettese” szövegrész helyébe a „kollégiumvezető-helyettese és"
        }
    ],
    "2013. évi CCXLVIII. törvény": [
        {
            "needle": "1.1. ”AIP” or Aeronautical Information Publication means the collection and dissemination of all",
            "replacement": "1.1. “AIP” or Aeronautical Information Publication means the collection and dissemination of all"
        },
        {
            "needle": "1.2. ”ANS” or Air Navigation Services for the purpose of this Agreement includes Air Traffic Management",
            "replacement": "1.2. “ANS” or Air Navigation Services for the purpose of this Agreement includes Air Traffic Management"
        },
        {
            "needle": "1.3. ”ANSP” or Air Navigation Service Provider means any public or private entity providing air navigation",
            "replacement": "1.3. “ANSP” or Air Navigation Service Provider means any public or private entity providing air navigation"
        },
        {
            "needle": "1.4. ”Appropriate NATO CAOC” means the competent NATO Combined Air Operations Centre.",
            "replacement": "1.4. “Appropriate NATO CAOC” means the competent NATO Combined Air Operations Centre."
        },
        {
            "needle": "1.5. ”Assignment” means the preparatory works and service provision carried out on the basis of this",
            "replacement": "1.5. “Assignment” means the preparatory works and service provision carried out on the basis of this"
        },
        {
            "needle": "1.6. ”ATM” means ATS, Airspace Management and Air Traffic Flow Management.",
            "replacement": "1.6. “ATM” means ATS, Airspace Management and Air Traffic Flow Management."
        },
        {
            "needle": "1.7. ”ATS” means area control service flight information service and alerting service.",
            "replacement": "1.7. “ATS” means area control service flight information service and alerting service."
        },
        {
            "needle": "1.8. ”Designated Airspace” shall have the meaning attributed thereto under Article 3.",
            "replacement": "1.8. “Designated Airspace” shall have the meaning attributed thereto under Article 3."
        },
        {
            "needle": "1.9. ”FIR” stands for Flight Information Region which is an airspace of defined dimensions within which",
            "replacement": "1.9. “FIR” stands for Flight Information Region which is an airspace of defined dimensions within which"
        },
        {
            "needle": "1.10. ”GAT” or General Air Traffic means flights conducted in accordance with the rules and provisions of",
            "replacement": "1.10. “GAT” or General Air Traffic means flights conducted in accordance with the rules and provisions of"
        },
        {
            "needle": "1.11. ”ICAO Class C Airspace” means aircraft operations may be conducted under Instrument Flight Rules",
            "replacement": "1.11. “ICAO Class C Airspace” means aircraft operations may be conducted under Instrument Flight Rules"
        },
        {
            "needle": "1.12. ”NSA” stands for National Supervisory Authority. For the purpose of this Agreement, NSA means the",
            "replacement": "1.12. “NSA” stands for National Supervisory Authority. For the purpose of this Agreement, NSA means the"
        },
        {
            "needle": "1.13. ”OAT” or Operational Air Traffic means flights which do not comply with the provisions stated for",
            "replacement": "1.13. “OAT” or Operational Air Traffic means flights which do not comply with the provisions stated for"
        },
        {
            "needle": "1.14. ”Safety investigation” means a process conducted by a safety investigation authority for the purpose",
            "replacement": "1.14. “Safety investigation” means a process conducted by a safety investigation authority for the purpose"
        },
        {
            "needle": "1.15. ”SPINS” stands for Special Instructions is the Unclassified Special Instructions or specific information,",
            "replacement": "1.15. “SPINS” stands for Special Instructions is the Unclassified Special Instructions or specific information,"
        },
        {
            "needle": "1.16. ”State flights” are flights engaged in missions undertaken by government, military, customs and",
            "replacement": "1.16. “State flights” are flights engaged in missions undertaken by government, military, customs and"
        },
        {
            "needle": "1.17. ”TRA” stands for Temporary Restricted Area and refers to an airspace of defined dimensions in",
            "replacement": "1.17. “TRA” stands for Temporary Restricted Area and refers to an airspace of defined dimensions in"
        },
        {
            "needle": "1.18. ”SIA” stands for Safety Investigation Authority. For the purpose of this Agreement, the SIA means the",
            "replacement": "1.18. “SIA” stands for Safety Investigation Authority. For the purpose of this Agreement, the SIA means the"
        },
        {
            "needle": "1.19. ”UAV/RPA” stands for Unmanned Aerial Vehicle/Remotely Piloted Aircraft.",
            "replacement": "1.19. “UAV/RPA” stands for Unmanned Aerial Vehicle/Remotely Piloted Aircraft."
        },
        {
            "needle": "P2 – Intersection of SKOPJE FIR, 41 52 37N 020 35 37E ”Triple Point” – SKOPJE FIR, TIRANA",
            "replacement": "P2 – Intersection of SKOPJE FIR, 41 52 37N 020 35 37E “Triple Point” – SKOPJE FIR, TIRANA"
        },
        {
            "needle": "1.1. ”AIP” vagy Aeronautical Information Publication (Légiforgalmi Tájékoztató Kiadvány) jelenti az összes",
            "replacement": "1.1. “AIP” vagy Aeronautical Information Publication (Légiforgalmi Tájékoztató Kiadvány) jelenti az összes"
        },
        {
            "needle": "1.2. ”ANS” vagy Air Navigation Services (Léginavigációs Szolgálatok) jelen Megállapodás céljaira magában",
            "replacement": "1.2. “ANS” vagy Air Navigation Services (Léginavigációs Szolgálatok) jelen Megállapodás céljaira magában"
        },
        {
            "needle": "1.3. ”ANSP” vagy Air Navigation Service Provider (Léginavigációs Szolgáltató) jelenti az általános légiforgalom",
            "replacement": "1.3. “ANSP” vagy Air Navigation Service Provider (Léginavigációs Szolgáltató) jelenti az általános légiforgalom"
        },
        {
            "needle": "1.4. ”A megfelelő NATO CAOC” jelentése az illetékes NATO Egyesített Légi Műveleti Központ Combined Air",
            "replacement": "1.4. “A megfelelő NATO CAOC” jelentése az illetékes NATO Egyesített Légi Műveleti Központ Combined Air"
        },
        {
            "needle": "1.5. ”Megbízatás” jelenti a jelen Megállapodás alapján végrehajtott előkészítő tevékenység és a szolgálatok",
            "replacement": "1.5. “Megbízatás” jelenti a jelen Megállapodás alapján végrehajtott előkészítő tevékenység és a szolgálatok"
        },
        {
            "needle": "1.6. ”ATM” jelentése: ATS, Légtérgazdálkodás és Légiforgalmi Áramlásszervezés (Airspace Management és Air",
            "replacement": "1.6. “ATM” jelentése: ATS, Légtérgazdálkodás és Légiforgalmi Áramlásszervezés (Airspace Management és Air"
        },
        {
            "needle": "1.7. ”ATS” jelenti a Körzeti Irányító Szolgálatot, a Repüléstájékoztató szolgálatot és a riasztószolgálatot.",
            "replacement": "1.7. “ATS” jelenti a Körzeti Irányító Szolgálatot, a Repüléstájékoztató szolgálatot és a riasztószolgálatot."
        },
        {
            "needle": "1.8. A ”Kijelölt Légtér” jelentése a 3. cikkben meghatározott jelentés.",
            "replacement": "1.8. A “Kijelölt Légtér” jelentése a 3. cikkben meghatározott jelentés."
        },
        {
            "needle": "1.9. ”FIR” jelentése a Repüléstájékoztató Körzet (Flight Information Region - FIR), meghatározott kiterjedésű",
            "replacement": "1.9. “FIR” jelentése a Repüléstájékoztató Körzet (Flight Information Region - FIR), meghatározott kiterjedésű"
        },
        {
            "needle": "1.10. ”GAT” vagy General Air Traffic (Általános Légiforgalom) jelenti az ICAO szabályainak és rendelkezéseink",
            "replacement": "1.10. “GAT” vagy General Air Traffic (Általános Légiforgalom) jelenti az ICAO szabályainak és rendelkezéseink"
        },
        {
            "needle": "1.11. ”ICAO Class C Airspace” (ICAO C osztályú légtér) jelenti, hogy légijármű üzemeltetés végezhető a Műszer",
            "replacement": "1.11. “ICAO Class C Airspace” (ICAO C osztályú légtér) jelenti, hogy légijármű üzemeltetés végezhető a Műszer"
        },
        {
            "needle": "1.12. ”NSA” jelentése a Nemzeti Felügyeleti Hatóság (National Supervisory Authority). Jelen Megállapodás",
            "replacement": "1.12. “NSA” jelentése a Nemzeti Felügyeleti Hatóság (National Supervisory Authority). Jelen Megállapodás"
        },
        {
            "needle": "1.13. ”OAT” vagy Műveleti Légiforgalom (Operational Air Traffic) jelenti a GAT vonatkozásában meghatározott",
            "replacement": "1.13. “OAT” vagy Műveleti Légiforgalom (Operational Air Traffic) jelenti a GAT vonatkozásában meghatározott"
        },
        {
            "needle": "1.14. ”Eseményvizsgálat” a balesetek és repülőesemények megelőzése céljából az eseményvizsgálatokat végző",
            "replacement": "1.14. “Eseményvizsgálat” a balesetek és repülőesemények megelőzése céljából az eseményvizsgálatokat végző"
        },
        {
            "needle": "1.15. ”SPINS” jelenti a megfelelő NATO testületek által közzétett Speciális Utasításokat (Special Instructions),",
            "replacement": "1.15. “SPINS” jelenti a megfelelő NATO testületek által közzétett Speciális Utasításokat (Special Instructions),"
        },
        {
            "needle": "1.16. ”Állami repülések” (State flights) azok a műveleti repülések, amelyeket kormányzati, katonai, vámügyi és",
            "replacement": "1.16. “Állami repülések” (State flights) azok a műveleti repülések, amelyeket kormányzati, katonai, vámügyi és"
        },
        {
            "needle": "1.17. ”TRA” jelentése Időszakosan Korlátozott Légtér (Temporary Restricted Area), amely a kijelölt légtérben egy",
            "replacement": "1.17. “TRA” jelentése Időszakosan Korlátozott Légtér (Temporary Restricted Area), amely a kijelölt légtérben egy"
        },
        {
            "needle": "1.18. ”SIA” jelenti az Eseményvizsgálatokat Végző Hatóságot (Safety Investigation Authority). Jelen Megállapodás",
            "replacement": "1.18. “SIA” jelenti az Eseményvizsgálatokat Végző Hatóságot (Safety Investigation Authority). Jelen Megállapodás"
        },
        {
            "needle": "1.19. ”UAV/RPA” jelentése pilóta nélküli légijármű / távvezérelt légijármű (Unmanned Aerial Vehicle/Remotely",
            "replacement": "1.19. “UAV/RPA” jelentése pilóta nélküli légijármű / távvezérelt légijármű (Unmanned Aerial Vehicle/Remotely"
        },
        {
            "needle": "P2 – SKOPJE FIR, TIRANA FIR & 41 52 37N 020 35 37E „Hármas pont“ – SKOPJE FIR, TIRANA",
            "replacement": "P2 – SKOPJE FIR, TIRANA FIR & 41 52 37N 020 35 37E „Hármas pont” – SKOPJE FIR, TIRANA"
        },
        {
            "needle": "1 A „Közigazgatási határvonal” a Nemzetközi Biztonsági Erő ( „KFOR“) és a Jugoszláv Szövetségi Köztársaság, illetve a Szerb Köztársaság kormányai",
            "replacement": "1 A „Közigazgatási határvonal” a Nemzetközi Biztonsági Erő ( „KFOR”) és a Jugoszláv Szövetségi Köztársaság, illetve a Szerb Köztársaság kormányai"
        },
        {
            "needle": "„Költségalap“) hoz létre, amely tartalmazza a léginavigációs szolgálatokkal kapcsolatban felmerülő összes",
            "replacement": "„Költségalap”) hoz létre, amely tartalmazza a léginavigációs szolgálatokkal kapcsolatban felmerülő összes"
        },
        {
            "needle": "megkezdését megelőzően – az ANSP-nek külön dokumentumot ( „Alapelvek“) kell kiadnia, amelyben",
            "replacement": "megkezdését megelőzően – az ANSP-nek külön dokumentumot ( „Alapelvek”) kell kiadnia, amelyben"
        }
    ],
    "2013. évi CCXXXI. törvény": [
        {
            "needle": "a már csökkentett összeget tartalmazza” szöveg lép.”",
            "replacement": "a már csökkentett összeget tartalmazza” szöveg lép."
        }
    ],
    "2013. évi CCXXXVI. törvény": [
        {
            "needle": "által alkalmazott módszerről,”",
            "replacement": "által alkalmazott módszerről,"
        },
        {
            "needle": "183/A. § (1) Az MNB a 33. § (1) bekezdésének megfelelően – a (2), a (3) vagy a (4) bekezdésben foglalt eltéréssel –",
            "replacement": "„183/A. § (1) Az MNB a 33. § (1) bekezdésének megfelelően – a (2), a (3) vagy a (4) bekezdésben foglalt eltéréssel –"
        }
    ],
    "2013. évi CLII. törvény": [
        {
            "needle": "”I have the honour to refer to paragraph 2 of Article 7 of the Agreement between Japan and Hungary on Social",
            "replacement": "“I have the honour to refer to paragraph 2 of Article 7 of the Agreement between Japan and Hungary on Social"
        },
        {
            "needle": "”I have the honour to refer to the Agreement between Japan and Hungary on Social Security which was signed",
            "replacement": "“I have the honour to refer to the Agreement between Japan and Hungary on Social Security which was signed"
        }
    ],
    "2013. évi CLXIII. törvény": [
        {
            "needle": "(hereinafter referred to as „Hungarian tax“);",
            "replacement": "(hereinafter referred to as „Hungarian tax”);"
        },
        {
            "needle": "(hereinafter referred to as „Swiss tax“).",
            "replacement": "(hereinafter referred to as „Swiss tax”)."
        },
        {
            "needle": "a) (i) the term „Hungary“ means the territory of Hungary as defined by its laws in accordance with",
            "replacement": "a) (i) the term „Hungary” means the territory of Hungary as defined by its laws in accordance with"
        },
        {
            "needle": "(ii) the term „Switzerland“ means the territory of the Swiss Confederation as defined by its laws in",
            "replacement": "(ii) the term „Switzerland” means the territory of the Swiss Confederation as defined by its laws in"
        },
        {
            "needle": "b) the term „person“ includes an individual, a company and any other body of persons;",
            "replacement": "b) the term „person” includes an individual, a company and any other body of persons;"
        },
        {
            "needle": "c) the term „company“ means any body corporate or any entity which is treated as a body corporate for tax",
            "replacement": "c) the term „company” means any body corporate or any entity which is treated as a body corporate for tax"
        },
        {
            "needle": "d) the terms „enterprise of a Contracting State“ and „enterprise of the other Contracting State“ mean",
            "replacement": "d) the terms „enterprise of a Contracting State” and „enterprise of the other Contracting State” mean"
        },
        {
            "needle": "e) the term „international traffic“ means any transport by a ship or aircraft operated by an enterprise that has",
            "replacement": "e) the term „international traffic” means any transport by a ship or aircraft operated by an enterprise that has"
        },
        {
            "needle": "f) the term „competent authority“ means:",
            "replacement": "f) the term „competent authority” means:"
        },
        {
            "needle": "g) the term „national“ in relation to a Contracting State means:",
            "replacement": "g) the term „national” in relation to a Contracting State means:"
        },
        {
            "needle": "1. For the purposes of this Convention, the term „resident of a Contracting State“ means any person who, under",
            "replacement": "1. For the purposes of this Convention, the term „resident of a Contracting State” means any person who, under"
        },
        {
            "needle": "1. For the purposes of this Convention, the term „permanent establishment“ means a fixed place of business through",
            "replacement": "1. For the purposes of this Convention, the term „permanent establishment” means a fixed place of business through"
        },
        {
            "needle": "2. The term „permanent establishment“ includes especially:",
            "replacement": "2. The term „permanent establishment” includes especially:"
        },
        {
            "needle": "4. Notwithstanding the preceding provisions of this Article, the term „permanent establishment“ shall be deemed not",
            "replacement": "4. Notwithstanding the preceding provisions of this Article, the term „permanent establishment” shall be deemed not"
        },
        {
            "needle": "2. The term „immovable property“ shall have the meaning which it has under the law of the Contracting State in which",
            "replacement": "2. The term „immovable property” shall have the meaning which it has under the law of the Contracting State in which"
        },
        {
            "needle": "5. The term „dividends“ as used in this Article means income from shares, „jouissance“ shares or „jouissance“ rights,",
            "replacement": "5. The term „dividends” as used in this Article means income from shares, „jouissance” shares or „jouissance” rights,"
        },
        {
            "needle": "2. The term „interest“ as used in this Article means income from debt-claims of every kind, whether or not secured by",
            "replacement": "2. The term „interest” as used in this Article means income from debt-claims of every kind, whether or not secured by"
        },
        {
            "needle": "2. The term „royalties“ as used in this Article means payments of any kind received as a consideration for the use of,",
            "replacement": "2. The term „royalties” as used in this Article means payments of any kind received as a consideration for the use of,"
        },
        {
            "needle": "2. The term „professional services“ includes especially independent scientific, literary, artistic, educational or teaching",
            "replacement": "2. The term „professional services” includes especially independent scientific, literary, artistic, educational or teaching"
        },
        {
            "needle": "It is understood that the term „pensions“ as used in Article 18 does not only cover periodic payments, but also",
            "replacement": "It is understood that the term „pensions” as used in Article 18 does not only cover periodic payments, but also"
        },
        {
            "needle": "In case of Switzerland, the term „pensions“ also includes payments from individual recognized pension schemes",
            "replacement": "In case of Switzerland, the term „pensions” also includes payments from individual recognized pension schemes"
        }
    ],
    "2013. évi CLXXXVI. törvény": [
        {
            "needle": "o) 85. § (4) és (5) bekezdésében a tagállamának” szövegrész helyébe a „tagállam”,",
            "replacement": "o) 85. § (4) és (5) bekezdésében a „tagállamának” szövegrész helyébe a „tagállam”,"
        },
        {
            "needle": "p) 85. § (7) bekezdésében a tagállamával” szövegrész helyébe a „tagállammal”",
            "replacement": "p) 85. § (7) bekezdésében a „tagállamával” szövegrész helyébe a „tagállammal”"
        }
    ],
    "2013. évi CXCVIII. törvény": [
        {
            "needle": "b) 54. § (1) bekezdésében az „– a kérelem írásban történő visszavonásától eltérő okból –” szövegrész.”",
            "replacement": "b) 54. § (1) bekezdésében az „– a kérelem írásban történő visszavonásától eltérő okból –” szövegrész."
        }
    ],
    "2013. évi CXLIII. törvény": [
        {
            "needle": "a) 3. § (6) bekezdésében a „Pénzügyi Szervezetek Állami Felügyelete (a továbbiakban: Felügyelet) szövegrész",
            "replacement": "a) 3. § (6) bekezdésében a „Pénzügyi Szervezetek Állami Felügyelete (a továbbiakban: Felügyelet)” szövegrész"
        }
    ],
    "2013. évi CXXV. törvény": [
        {
            "needle": "ajánlatot vagy nyújthatnak be részvételi jelentkezést.’’",
            "replacement": "ajánlatot vagy nyújthatnak be részvételi jelentkezést.”"
        }
    ],
    "2013. évi LII. törvény": [
        {
            "needle": "(3) E törvény 2013. július 2-án hatályát veszti.”",
            "replacement": "(3) E törvény 2013. július 2-án hatályát veszti."
        }
    ],
    "2013. évi LXXII. törvény": [
        {
            "needle": "szöveg lép.”",
            "replacement": "szöveg lép."
        }
    ],
    "2013. évi LXXXVII. törvény": [
        {
            "needle": "évi LXXXVII. törvénnyel megállapított rendelkezéseit 2014. január 1-jétől kell alkalmazni.",
            "replacement": "évi LXXXVII. törvénnyel megállapított rendelkezéseit 2014. január 1-jétől kell alkalmazni.”"
        }
    ],
    "2013. évi VII. törvény": [
        {
            "needle": "„KORLÁTOZOTT TERJESZTÉSŰ!“ DIFFUSION RESTREINTE",
            "replacement": "„KORLÁTOZOTT TERJESZTÉSŰ!” DIFFUSION RESTREINTE"
        }
    ],
    "2013. évi XLI. törvény": [
        {
            "needle": "Foglalkoztatási Alap negyedévente megtéríti az Egészségbiztosítási Alap részére.”",
            "replacement": "Foglalkoztatási Alap negyedévente megtéríti az Egészségbiztosítási Alap részére."
        },
        {
            "needle": "b) 39. § (2) bekezdésében az „s)–v) pontja szövegrész helyébe az „s)–w) pontja” szöveg,",
            "replacement": "b) 39. § (2) bekezdésében az „s)–v) pontja” szövegrész helyébe az „s)–w) pontja” szöveg,"
        }
    ],
    "2013. évi XX. törvény": [
        {
            "needle": ",,(4) A 3. § (4) bekezdése szerinti esetben az OBH elnöke a kinevezésre vonatkozó javaslatának felterjesztése előtt",
            "replacement": "„(4) A 3. § (4) bekezdése szerinti esetben az OBH elnöke a kinevezésre vonatkozó javaslatának felterjesztése előtt"
        }
    ],
    "2013. évi XXI. törvény": [
        {
            "needle": "helyébe a „miniszter” szöveg lép.”",
            "replacement": "helyébe a „miniszter” szöveg lép."
        }
    ],
    "2014. évi CVI. törvény": [
        {
            "needle": "a „letett” szöveg”,",
            "replacement": "a „letett” szöveg,"
        }
    ],
    "2014. évi LIII. törvény": [
        {
            "needle": "”the Parties”) have approved an Arrangement on the operation of a Working Holiday Scheme (hereinafter referred",
            "replacement": "“the Parties”) have approved an Arrangement on the operation of a Working Holiday Scheme (hereinafter referred"
        },
        {
            "needle": "to as ”the Scheme”) between the Parties. The purpose of the Scheme is to enhance cultural and people-to-people",
            "replacement": "to as “the Scheme”) between the Parties. The purpose of the Scheme is to enhance cultural and people-to-people"
        },
        {
            "needle": "(a) ”Taiwan” means the territory in respect of which the immigration laws administered by the Ministry of the",
            "replacement": "(a) “Taiwan” means the territory in respect of which the immigration laws administered by the Ministry of the"
        },
        {
            "needle": "(b) ”Hungary” means the territory in respect of which Hungarian immigration laws are applied at the date of the",
            "replacement": "(b) “Hungary” means the territory in respect of which Hungarian immigration laws are applied at the date of the"
        },
        {
            "needle": "a ”working holiday visa”), valid for a period of twelve (12) months from the date of issue, to any person who satisfies",
            "replacement": "a “working holiday visa”), valid for a period of twelve (12) months from the date of issue, to any person who satisfies"
        },
        {
            "needle": "A tajpeji Magyar Kereskedelmi Iroda és a Magyarországi Tajpej Képviseleti Iroda (a továbbiakban: ,,Szerződő",
            "replacement": "A tajpeji Magyar Kereskedelmi Iroda és a Magyarországi Tajpej Képviseleti Iroda (a továbbiakban: „Szerződő"
        },
        {
            "needle": "Felek”) az ideiglenesen munkát vállaló turisták programjáról szóló Megállapodás (a továbbiakban: ,,Program”)",
            "replacement": "Felek”) az ideiglenesen munkát vállaló turisták programjáról szóló Megállapodás (a továbbiakban: „Program”)"
        }
    ],
    "2014. évi LVII. törvény": [
        {
            "needle": "„",
            "replacement": "”"
        }
    ],
    "2014. évi LXII. törvény": [
        {
            "needle": "(2) ,,A helyi önkormányzatok általános működésének és ágazati feladatainak támogatása” cím előirányzatait és",
            "replacement": "(2) „A helyi önkormányzatok általános működésének és ágazati feladatainak támogatása” cím előirányzatait és"
        },
        {
            "needle": ",,a helyi önkormányzatok általános működésének és ágazati feladatainak támogatása” címen megillető, és a részükre",
            "replacement": "„a helyi önkormányzatok általános működésének és ágazati feladatainak támogatása” címen megillető, és a részükre"
        }
    ],
    "2014. évi LXXIV. törvény": [
        {
            "needle": "a „2013. január 1-jétől” szövegrész helyébe a „2013. július 1-jétől” szöveg, a 2015. január 1-jével” szövegrész",
            "replacement": "a „2013. január 1-jétől” szövegrész helyébe a „2013. július 1-jétől” szöveg, a „2015. január 1-jével” szövegrész"
        }
    ],
    "2014. évi VI. törvény": [
        {
            "needle": "ОРГАНИЗАЦИИ КОСМИЧЕСКОЙ СВЯЗИ ”ИНТЕРСПУТНИК”",
            "replacement": "ОРГАНИЗАЦИИ КОСМИЧЕСКОЙ СВЯЗИ “ИНТЕРСПУТНИК”"
        }
    ],
    "2014. évi XCIII. törvény": [
        {
            "needle": "d) „133. § (2) bekezdésében az „a helyi önkormányzat működésére” szövegrész helyébe az „az érintett",
            "replacement": "d) 133. § (2) bekezdésében az „a helyi önkormányzat működésére” szövegrész helyébe az „az érintett"
        }
    ],
    "2014. évi XI. törvény": [
        {
            "needle": "meg.”” szövegrész helyébe az „* A rezsicsökkentés a fogyasztókat a 2012. április 14. napján alkalmazott díj",
            "replacement": "meg.” szövegrész helyébe az „* A rezsicsökkentés a fogyasztókat a 2012. április 14. napján alkalmazott díj"
        }
    ],
    "2014. évi XLIV. törvény": [
        {
            "needle": "a) ”Aeronautical Authority” means in the case of the Government of the United Arab Emirates (UAE), the",
            "replacement": "a) “Aeronautical Authority” means in the case of the Government of the United Arab Emirates (UAE), the"
        },
        {
            "needle": "b) ”Agreed Services” means scheduled international air services which can be operated for the transport",
            "replacement": "b) “Agreed Services” means scheduled international air services which can be operated for the transport"
        },
        {
            "needle": "c) ”Agreement” means this Agreement, its Annexes and any amendments thereto;",
            "replacement": "c) “Agreement” means this Agreement, its Annexes and any amendments thereto;"
        },
        {
            "needle": "d) ”Convention” means the Convention on International Civil Aviation, opened for signature at Chicago on",
            "replacement": "d) “Convention” means the Convention on International Civil Aviation, opened for signature at Chicago on"
        },
        {
            "needle": "e) ”Air Service”, “Airline”, ”International Air Service” and ”stop for non traffic purposes” have the meanings",
            "replacement": "e) “Air Service”, “Airline”, ”International Air Service” and ”stop for non traffic purposes” have the meanings"
        },
        {
            "needle": "f) ”Annexes” shall include provisions annexed to the Agreement such as the Route Schedule, the List of",
            "replacement": "f) “Annexes” shall include provisions annexed to the Agreement such as the Route Schedule, the List of"
        },
        {
            "needle": "g) ”Designated Airlines” means an airline or airlines that have been designated and authorized in accordance",
            "replacement": "g) “Designated Airlines” means an airline or airlines that have been designated and authorized in accordance"
        },
        {
            "needle": "i) ”Territory” in relation to a State has the meaning assigned to it in Article 2 of the Convention;",
            "replacement": "i) “Territory” in relation to a State has the meaning assigned to it in Article 2 of the Convention;"
        },
        {
            "needle": "l) References in this Agreement to the ”EU Treaties” shall be understood as referring to the Treaty on European",
            "replacement": "l) References in this Agreement to the “EU Treaties” shall be understood as referring to the Treaty on European"
        },
        {
            "needle": "called ”ramp inspection”), provided this does not lead to unreasonable delay.",
            "replacement": "called “ramp inspection”), provided this does not lead to unreasonable delay."
        },
        {
            "needle": "e) “Air Service”, “Airline”, ”International Air Service” and ”stop for non traffic purposes” have the meanings",
            "replacement": "e) “Air Service”, “Airline”, “International Air Service” and “stop for non traffic purposes” have the meanings"
        },
        {
            "needle": "légitársaságai üzemeltetik.",
            "replacement": "légitársaságai üzemeltetik.”"
        }
    ],
    "2014. évi XLIX. törvény": [
        {
            "needle": "(a) in Bahrain, to income tax payable under Amiri Decree No. 22/1979 (hereinafter referred to as ”Bahrain Tax”);",
            "replacement": "(a) in Bahrain, to income tax payable under Amiri Decree No. 22/1979 (hereinafter referred to as “Bahrain Tax”);"
        }
    ],
    "2014. évi XXXIX. törvény": [
        {
            "needle": ",,(4) Az ajánlat az egyetemes szolgáltatásra jogosult azon felhasználók ellátásához szükséges földgázmennyiség",
            "replacement": "„(4) Az ajánlat az egyetemes szolgáltatásra jogosult azon felhasználók ellátásához szükséges földgázmennyiség"
        }
    ],
    "2015. évi CIV. törvény": [
        {
            "needle": "„Felhatalmazás",
            "replacement": "Felhatalmazás"
        },
        {
            "needle": "28. § Felhatalmazást kap a Kormány, hogy e törvény alapján",
            "replacement": "„28. § Felhatalmazást kap a Kormány, hogy e törvény alapján"
        }
    ],
    "2016. évi CLXXIX. törvény": [
        {
            "needle": "tizenöt nappal követő időpontra hívják össze.”",
            "replacement": "tizenöt nappal követő időpontra hívják össze."
        }
    ],
    "2016. évi CLXXXIV. törvény": [
        {
            "needle": "„143. § (1) Árvák kiegészítő támogatására jogosult az állomány elhunyt tagjának – ideértve a 224. § (3) bekezdése",
            "replacement": "143. § (1) Árvák kiegészítő támogatására jogosult az állomány elhunyt tagjának – ideértve a 224. § (3) bekezdése"
        },
        {
            "needle": "a) az önkéntes tartalékos katona hivatásos, szerződéses, honvéd tisztjelölt vagy honvéd altiszt-jelölt szolgálati",
            "replacement": "„a) az önkéntes tartalékos katona hivatásos, szerződéses, honvéd tisztjelölt vagy honvéd altiszt-jelölt szolgálati"
        }
    ],
    "2018. évi LI. törvény": [
        {
            "needle": "Maďarsko a Slovenská republika (ďalej len „zmluvné strany“),",
            "replacement": "Maďarsko a Slovenská republika (ďalej len „zmluvné strany”),"
        },
        {
            "needle": "slovenskej hraničnej čiary – hraničné úseky č. III., IV. a VIII. – 2013“, ktorý ako príloha tejto zmluvy tvorí jej",
            "replacement": "slovenskej hraničnej čiary – hraničné úseky č. III., IV. a VIII. – 2013”, ktorý ako príloha tejto zmluvy tvorí jej"
        },
        {
            "needle": "MAĎARSKO SLOVENSKÚ REPUBLIKU“",
            "replacement": "MAĎARSKO SLOVENSKÚ REPUBLIKU”"
        }
    ],
    "2018. évi LII. törvény": [
        {
            "needle": "3. a szociális igazgatásról és szociális ellátásokról szóló 1993. évi III. törvény 4. § (1c) pontjában az „egészségügyi",
            "replacement": "3. a szociális igazgatásról és szociális ellátásokról szóló 1993. évi III. törvény 4. § (1c) bekezdésében az „egészségügyi"
        }
    ]
}
